### ISSUE TITLE
UNCS List Creation Problem

### ISSUE THREAD

**Issue by Datadep5** [BSData/halo-fleet-battles#2]
I tried to create a new UNSC list with the new app.  Each attempt to make a new list kicks me back to the starting page of the app.  This does not occur with the Covenant fleet.

**Comment by KealL** [comment]
Hi Datadep5
Could you provide some more info as I am unable to duplicate the issue?

Device?
Version of UNSC?

Thanks

**Comment by Datadep5** [comment]
Samsung Note 5
UNSC 18

After I have selected the UNSC Fleet v18 I come to a 'Create Roster' screen
where I need to click the check mark in the upper left hand corner.  When I
do it shows me a popup window that goes away too quickly for me to read.

Also I'm using Version 2.00.04 of the new Battlescribe.

**Comment by KealL** [comment]
Resolved please update to UNSC v19
