### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by dsmize2011** [BSData/halo-fleet-battles#4]
I would like to be able to help maintain the Halo fleet battles data... It is outdated at this point and no one seems to be updating it anymore. 
-Thanks

**Comment by amis92** [comment]
Hello, @dsmize2011 . Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
